# Generated by Django 4.0.10 on 2024-05-27 22:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('counsellor', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(max_length=100)),
                ('how_did_you_find_us', models.CharField(blank=True, max_length=255, null=True)),
                ('level_of_education', models.CharField(max_length=100)),
                ('level_of_interest', models.CharField(max_length=100)),
                ('area_of_interest', models.CharField(max_length=100)),
                ('program_of_interest', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('country_of_interest', models.CharField(max_length=100)),
                ('intake', models.CharField(max_length=4)),
                ('information', models.CharField(blank=True, max_length=10, null=True)),
                ('documents', models.CharField(blank=True, max_length=10, null=True)),
                ('application', models.CharField(blank=True, max_length=10, null=True)),
                ('offer_letter', models.CharField(blank=True, max_length=10, null=True)),
                ('scholarship', models.TextField(blank=True, null=True)),
                ('acceptance', models.CharField(blank=True, max_length=10, null=True)),
                ('payment', models.CharField(blank=True, max_length=10, null=True)),
                ('coe', models.CharField(blank=True, max_length=10, null=True)),
                ('visa', models.CharField(blank=True, max_length=10, null=True)),
                ('invoice', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('visa_resolution_time', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('total_tuition', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yearly_tuition', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
